### ISSUE TITLE
Commandp "nil" when no selection

### ISSUE THREAD

**Issue by llcc** [rejeep/wrap-region.el#28]
Calling the command without any selection can cause commandp error.
Actually I think it will be more sensible if it just invoke insert command rather than region warp when no selection.

For instance in org-mode if i want to input oxygen O_2, 
```
if i just type _ behind O, only _ should be inserted to O_.       
if I select O, then type _, it should change to _O_.
```

Thanks if you can consider this.

**Comment by rejeep** [comment]
If no region, then wrap-region will fallback. See https://github.com/rejeep/wrap-region.el/blob/master/wrap-region.el#L156

I cant reproduce this. Try and clone this repo and do:

```bash
$ cask exec emacs -Q -nw --load wrap-region.el --eval '(progn (org-mode) (wrap-region-mode 1) (insert "foo O bar"))'
```

If you place the cursor behind `O` and press a wrap-key. Does it happen then?

**Comment by llcc** [comment]
Hi @rejeep,

It works well if i do as what you say. But I can not make it work in my Emacs. I got these error message:

```
 call-interactively(nil)
  wrap-region-fallback(" _")
  wrap-region-trigger(1 " _")
  (lambda (arg) (interactive "p") (wrap-region-trigger arg " _"))(1)
  call-interactively((lambda (arg) (interactive "p") (wrap-region-trigger arg " _")) nil nil)
  command-execute((lambda (arg) (interactive "p") (wrap-region-trigger arg " _")))
```

What's the problem?

**Comment by llcc** [comment]
Sorry to disturb by this issue. I finally found that it was my configuration causing this problem. 
Now, problem fixed.

**Comment by rejeep** [comment]
:+1:
