### ISSUE TITLE
undo problem

### ISSUE THREAD

**Issue by hmelman** [rejeep/wrap-region.el#29]
Currently in markdown-mode with wrap-region-mode enabled, if I set a region and type * I get an asterisk added at the beginning and end of region with the region still active (so that I could add another pair). If I deactivate region (C-g) and then undo, both asterisks are removed. However if I don't deactivate region and undo immediately after typing * then only one of the asterisks is removed. I think both should be removed even if I don't deactivate region.

**Comment by rejeep** [comment]
I don't get this behaviour. Can you please write a [feature](https://github.com/rejeep/wrap-region.el/tree/master/features) that reproduces the issue?

**Comment by hmelman** [comment]
Hmm, I can no longer reproduce it. I still see the same behavior if I deactivate region. Now if I keep the region active, I just get a message in the echo area saying: "Undo in region!" which I've learned means undo is doing Selective Undo and since the asterisks are added outside of region, there's nothing to undo.

I've been testing with marking a word, I see slightly different behavior if I mark it via set-mark-command, forward-word and if I use er/expand-region. I'm not sure what I did originally and I'm not seeing consistent results now.

I'm not familiar with writing features (though it looks simple enough). If you can't reproduce the above, I'm fine with you closing this until I can reliably reproduce it with a feature.

**Comment by rejeep** [comment]
Closing this until someone has a way to reproduce this.
