### ISSUE TITLE
wrap-region-trigger-replace

### ISSUE THREAD

**Issue by djangoliv** [rejeep/wrap-region.el#30]
That'd be interesting to be able to replace a wrapper by another one.
For example:
- (region) => "(region)" (with " key) 
- (region) => "region" (with C-" key)

Thanks a lot for that mode, btw.

**Comment by rejeep** [comment]
This is too complex for wrap-region. I recommend using [Smartparens](https://github.com/Fuco1/smartparens) for more advance usage. See for example the function `sp-rewrap-sexp`.
